version: '3.7'
services:
  test:
    build:
      context: ./scripts
      dockerfile: Dockerfile
    networks:
      app-network:

networks:
  app-network:
    external:
      name: log-routing-service_app-network
